# create deployment by using below spec
# kubectl apply -f deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: spring-deployment
  template:
    metadata:
      labels:
        app: spring-deployment
    spec:
      containers:
      - name: spring-deployment
        image: springio/gs-spring-boot-docker
        ports:
        - containerPort: 8080
