#create service for deployment.
#kubectl apply -f service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  type: LoadBalancer
  selector:
    app: spring-deployment
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31276
