# https://dev.to/musolemasu/deploy-a-mysql-database-server-in-kubernetes-static-dpc
# https://phoenixnap.com/kb/kubernetes-mysql

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"