apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
        - image: mysql:8.0.33
          name: mysql-deployment
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysqlrootpass"
            - name: MYSQL_USER
              value: "mysqluser"
            - name: MYSQL_PASSWORD
              value: "mysqlpass"
          ports:
            - containerPort: 3306
              name: mysql-deployment
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc